name: release

on:
  push:
    branches: [master]
    paths:
      - manifest.json
  workflow_dispatch:

jobs:
  github-release:
    name: github-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/scripts/create-github-release.sh
